### ISSUE TITLE
Python 3.8.5 - parsing issues

### ISSUE THREAD

**Issue by tormodb** [wowchemy/hugo-academic-cli#74] opened 2020-09-24 12:46 UTC
Hi! I am getting the following error when trying to use academic to import a bibtex file with publications into my blog: 

`TypeError: combining() argument must be a unicode character, not str`

I have previously managed to use the tool, can this be related to updates in python?

**Comment by gcushen** [comment] 2020-09-24 14:52
Duplicate of https://github.com/wowchemy/hugo-academic-cli/issues/54

**Closed by gcushen** 2020-09-24 14:52 UTC
