### ISSUE TITLE
academic 0.7.0 failed to import asserts for wowchemy 5.3.0

### ISSUE THREAD

**Issue by yzs981130** [wowchemy/hugo-academic-cli#98] opened 2021-08-15 11:36 UTC
I want to build an offline website by the instructions:
[Installing the Wowchemy Admin tool and running academic import --assets within your site’s folder may help with automatically downloading and concatenating JS and CSS assets.](https://wowchemy.com/docs/guide/offline-site) 

It failed with the error that are attached below.

```shell
➜  academic import --assets
07:29:09PM ERROR: Could not detect Academic version in `themes/academic/data/academic.toml`. You may need to update Academic in order to use this tool.
➜  cat go.mod
module github.com/wowchemy/starter-hugo-academic

go 1.15

require (
	github.com/wowchemy/wowchemy-hugo-modules/v5 v5.3.0
)
```

Related versions:

Hugo: v0.87.0 extended
wowchemy-hugo-modules: v5.3.0
hugo-academic-cli: v0.7.0 (installed by pip3 install -U git+https://github.com/wowchemy/hugo-academic-cli.git commit: 7f6e0cb)

**Comment by gcushen** [comment] 2021-08-15 15:00
Duplicate of https://github.com/wowchemy/wowchemy-hugo-modules/discussions/2413 and https://github.com/gohugoio/hugo/issues/8883

Feel free to leave your comments and feedback at https://github.com/gohugoio/hugo/issues/8883

**Closed by gcushen** 2021-08-15 15:00 UTC
